MAX_WORKERS = 150
MAX_NUMBER_SHELVES = 5

SHELVES_LOAD_FIRST_PAGE_ONLY = True
SHELVES_PAGES_TO_READ = 3

LISTS_PARSE_FIRST_PAGE_ONLY = True
LISTS_PARSE_PAGE_COUNT = 1
PARSE_LIST_FIST_PAGE_ONLY = True
LIST_PAGES_TO_PARSE = 1

GOODREADS_URL = 'https://www.goodreads.com'
SHELVES_PAGE = f'{GOODREADS_URL}/book/shelves'
LIST_PAGE = f'{GOODREADS_URL}/list/book'
